services:
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: s20-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alert-rules.yml:/etc/prometheus/alert-rules.yml:ro

  node-exporter:
    image: prom/node-exporter:v1.9.1
    container_name: s20-node-exporter
    ports:
      - "9100:9100"

  grafana:
    image: grafana/grafana:12.1.1
    container_name: s20-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
